### ISSUE TITLE
Typescript error when using the README log code

### ISSUE THREAD

**Issue by caewok** [League-of-Foundry-Developers/foundryvtt-devMode#8]
**Environment Details**
- Foundry Core Version: 0.7.9
- System & Version: dnd5e 1.2.4
- OS & Browser: Mac OS X 10.15.7, Firefox 87.0
- Hosting: 
(Docker. For compiling gulp / typescript, running ubuntu 20.04 on remote VM.) 

Forgive me, as I am fairly new to typescript and gulp. As such, I am not sure if I have the right solution or not, but I think the README should be updated to explain how to use the log() function with typescript.

**Describe the bug**
When I add the following code from the README to my project, I get the error `error TS2339: Property 'DEV' does not exist on type 'Window & typeof globalThis'.` when I run `gulp build`. 
```js
const MODULE_ID = 'my-module-id';

function log(force: boolean, ...args) {
  try {
    const isDebugging = window.DEV?.getPackageDebugValue(MODULE_ID);

    if (force || isDebugging) {
      console.log(MODULE_ID, '|', ...args);
    }
  } catch (e) {}
}
```
My tsconfig.json, in case it is relevant:
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "ES6",
    "lib": ["DOM", "ES6", "ES2017", "ES2018"],
    "types": ["@league-of-foundry-developers/foundry-vtt-types", "node"],
    "allowUmdGlobalAccess": true
  },
  "files": ["./gulpfile.ts"],
  "exclude": [
    "node_modules"
  ]
}

```
**Expected behavior**
I would expect the default example in the README to work with typescript without modification or with notes for how to modify it.

**Additional observations**
I think the reason for this error is [described here](https://blog.angular-university.io/typescript-2-type-system-how-does-it-really-work-when-are-two-types-compatible-its-actually-quite-different-than-other-type-systems/). Basically, the window global does not have a type defined for DEV (in fact, DEV is not defined until devMode is loaded). So typescript complains that I am trying to access the window.DEV.getPackageDebugValue() function because it cannot find a type for window.DEV. 

After some trial/error, I think the following modification works:
```js
let mywindow: any = window;
const isDebugging = mywindow.DEV?.getPackageDebugValue(MODULE_ID);
```
It might also be worth setting the expected type for isDebugging: `const isDebugging: boolean`, although this does not fix the error by itself.

**Comment by akrigline** [comment]
@caewok you've stumbled into one of the downfalls of Typescript and will either have to tell TS what `window.DEV` is expected to look like, or tell TS to ignore that line.

### Were I in your shoes this is how I would handle this:

```ts
//@ts-ignore
const isDebugging = window.DEV?.getPackageDebugValue(MODULE_ID) as boolean;
```

isDebugging will (probably) show up as a boolean for you, ts will not complain about `DEV` on `window`.

### Some more context for you.

Typescript is compiled down to javascript before it is run, all of the type information vanishes when this happens. This repo is written itself in typescript, but all of that information is thrown away after it is compiled and run in the browser.

Your own code doesn't preserve this information either, all Typescript is trying to do is catch errors before that point (i.e. at compile time, instead of at runtime). To do so, Typescript makes a lot of assumptions, most of these are handled for you and some of those include the shape of the `window` object.

The normal `window` object does not include our custom `DEV` property. So to make TS happy, you'd have to do something like this:
```ts
interface DevModeApi {
  getPackageDebugValue(packageName: string): boolean;
}

declare global {
    interface Window { DEV: DevModeApi; }
}
```

Please know that this is not an accurate type for the API, this is only partially accurate for your example.

Something I should definitely do is write some documentation about this and include an actual API Interface example.

**Comment by caewok** [comment]
Thanks; that is very helpful!
